In [2]:
import random
import numpy as np

In [1]:
ACTION_TABLE = {
    0: [0, 0, 0, 0],
    1: [0, 0, 0, 1]
}

In [3]:
np.zeros

<function numpy.zeros>

In [4]:
_size = [4,8]

# For random integers between 0 and 9
random_int_array = np.random.randint(0, 10, size=_size)
random_int_array

array([[0, 3, 4, 6, 9, 6, 9, 0],
       [4, 5, 2, 9, 2, 6, 3, 1],
       [7, 9, 0, 0, 0, 3, 7, 5],
       [1, 4, 5, 1, 9, 2, 3, 8]])

In [42]:
random_int_array[0:1, :]

array([[6, 4, 8, 1, 5, 4, 2, 9]])

In [5]:
np.roll(random_int_array, 1, axis=0)

array([[1, 4, 5, 1, 9, 2, 3, 8],
       [0, 3, 4, 6, 9, 6, 9, 0],
       [4, 5, 2, 9, 2, 6, 3, 1],
       [7, 9, 0, 0, 0, 3, 7, 5]])